### ISSUE TITLE
Request for Part 3

### ISSUE THREAD

**Issue by kakarot-dev** [vitorlfaria/rust_clean_api#1]
Im following your series in dev guide, and am absolutely loving it..
Since im from nodejs side of things, im pretty happy with what you have written out.

Can we get a eta on part 3?

**Comment by kakarot-dev** [comment]
That being said, i have two questions.
1. What is "Entity"?
![image](https://github.com/vitorlfaria/rust_clean_api/assets/76399483/bafdf1e7-d0f5-4c7c-bbae-bfde393da54c)
2. What is the need for `infrastructure/data`, couldnt you just have moved the folders to infrastructure instead of creating a folder for it?

**Comment by vitorlfaria** [comment]
I'm glad that you liked the series!
For "eta" you mean estimated time of arrival? For part 3 I'm planning something for authentication and authorization, but I'm not yet sure if I'll make it. I'm now making a desktop UI to consume this API with Tauri and I think about doing an article for it too. But it depends on what you guys want more.

Now for your other questions. Entity is just another name for model, but with a purpose of representing database entities, it's used more in dotnet world.

For the need for the `infrasctructure/data`, it's because in the infrastructure layer we can define other types of services and layers. One example would be a layer used to make integrations with external services, we can implement it in `infrastrucure/integrations/service_name`. That way our infrastructure layer will be more organized and well implemented.

**Comment by kakarot-dev** [comment]
My reason to read through the guide was to write clean code with a boiler plate for axum.
If your directly planning to switch to tauri, i personally think it wont be useful, that being said, im looking forward for the authentication part (as oauth stuff is annoying)
If you do decide on doing the authentication, please do give a eta on it.

> Now for your other questions. Entity is just another name for model, but with a purpose of representing database entities, it's used more in dotnet world.

I see entities are basically models then? im still new, sorry bout that

> For the need for the infrasctructure/data, it's because in the infrastructure layer we can define other types of services and layers. One example would be a layer used to make integrations with external services, we can implement it in infrastrucure/integrations/service_name. That way our infrastructure layer will be more organized and well implemented.

Thank you for the explanation!

**Comment by kakarot-dev** [comment]
Also, One more thing, in the second guide, there is no reference to the infrastructure folder in this part
![image](https://github.com/vitorlfaria/rust_clean_api/assets/76399483/2b67393a-20c6-4186-a09b-38e4e96496f5)

**Comment by vitorlfaria** [comment]
First, don't be sorry for asking questions about something you want to know, all the questions are valid.

I don't mean to change from Axum to Tauri, they have different purposes, Tauri is to build the front end as a Desktop app. And the back end is the Axum API.

In the second part I didn't use the complete path for the files, I just put `data/mod.rs` for you to know in what `mod.rs` is to implement the code, but it is still in `infrastructure/data/mod.rs`.

What you mean by "eta"?

**Comment by mj59735** [comment]
That's good news.I am also interested in Tauri, surrealdb, rust. I am new to rust and surrealdb. I have strong background in Java. Looking forward to Tauri desktop series. Thanks for providing all the details of this api based on Clean Architecture..

**Comment by kakarot-dev** [comment]
> First, don't be sorry for asking questions about something you want to know, all the questions are valid.

Thank you!
> I don't mean to change from Axum to Tauri, they have different purposes, Tauri is to build the front end as a Desktop app. And the back end is the Axum API.

Oho, but i meant wont it be a direct change in the series of axum? i mean if your gonna do it seperately thats pretty cool hehe :3
> In the second part I didn't use the complete path for the files, I just put `data/mod.rs` for you to know in what `mod.rs` is to implement the code, but it is still in `infrastructure/data/mod.rs`.

I see, guessed so from the source code
> What you mean by "eta"?
 
Do you have a timeline for when ya will work on part 3?

**Comment by vitorlfaria** [comment]
> Oho, but i meant wont it be a direct change in the series of axum? i mean if your gonna do it seperately thats pretty cool hehe :3

Oh I see. Yes, it would be a separate series, but using the API built in this series.

> Do you have a timeline for when ya will work on part 3?

Unfortunately I don't, I write at my spare time and my wife will give birth next days. So will see what I can do in the next weeks. But I have plans to do it.

**Comment by kakarot-dev** [comment]
> > Oho, but i meant wont it be a direct change in the series of axum? i mean if your gonna do it seperately thats pretty cool hehe :3
> 
> Oh I see. Yes, it would be a separate series, but using the API built in this series.

Ah okii!
> 
> > Do you have a timeline for when ya will work on part 3?
> 
> Unfortunately I don't, I write at my spare time and my wife will give birth next days. So will see what I can do in the next weeks. But I have plans to do it.

Congratulations!! Hope everything goes according to gods plan.
